curl --location 'https://api.openai.com/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${ApiKey}' \
--data '{
    "model": "gpt-4o-mini",
    "messages": [
      {
        "role": "user",
        "content": "Explique-moi les APIs en 3 phrases."
      }
    ]
  }'

  